import { Pool } from "../entry/GoPool";
export { init, frameReady, editable, gos, updateCurrentPoint, setWebsocket, getCurrentPos, setPool };
declare let editable: boolean[][];
declare let gos: HTMLDivElement[][];
declare function init(): void;
declare function setWebsocket(socket: WebSocket): void;
declare function setPool(p: Pool): void;
declare function updateCurrentPoint(x: number, y: number): void;
declare function getCurrentPos(): number[];
declare function frameReady(color: boolean): void;
